### ISSUE TITLE
Need support for Installing from custom_repo server  in restricted environments

### ISSUE THREAD

**Issue by tuxfight3r** [jmkeyes/puppet-kairosdb#3]
Need support for Installing from custom_repo server in restricted environments

**Comment by tuxfight3r** [comment]
This pull request https://github.com/jmkeyes/puppet-kairosdb/pull/2 facilitates that feature.

**Comment by jmkeyes** [comment]
PR merged.

**Comment by tuxfight3r** [comment]
Hi Jmkeyes,

Can you please bump the version in puppet forge, so we can use forge to
pull the code. thanks.

## 

Regards,
Mohan

---

```
    Regards,

    Mohan
```

**Comment by jmkeyes** [comment]
Done!
